version: '3'
services:
  server:
    build: './server'
    image: server 
    ports:
      - 8080:8080 #"3001:3000"
    depends_on: 
      - db
    environment:
      - MONGO_DB_URI=mongodb://db/WSIE
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db

volumes:
  mongodb_data:
